config/routes.rb
# frozen_string_literal: true

require 'api_constraints'

Rails.application.routes.draw do
  root to: 'home#index', via: :all

  # API
  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :sessions, only: :create
      resource :session, only: :destroy
      resources :locations, only: :create

      post 'search', to: 'restaurants#search'
      post 'preference', to: 'restaurants#preference'
    end
  end
end

app/models/location.rb
# frozen_string_literal: true

class Location
  include Mongoid::Document
  include Mongoid::Timestamps

  LOCATION_TYPES = %w[seeded acquired].freeze

  field :formatted_address, type: String
  field :street_name, type: String
  field :town, type: String
  field :county, type: String
  field :state, type: String
  field :country, type: String
  field :postal_code, type: String
  field :latitude, type: String
  field :longitude, type: String
  field :location_type, type: String

  # associations
  has_and_belongs_to_many :users, index: true

  # validations
  validates :location_type, inclusion: { in: LOCATION_TYPES, message: ' is not a valid location_type' }
  validates :latitude, :longitude, presence: true, if: :address_fields_empty?

  # callbacks

  # scopes
  scope :acquired, -> { where(location_type: 'acquired') }
  scope :default, -> { where(location_type: 'seeded') }

  def full_address
    formatted_address || attributes.slice('street_name', 'town', 'state', 'country', 'postal_code').values.reject(&:blank?).join(' ')
  end

  def address_fields_empty?
    postal_code.blank? && formatted_address.blank? && street_name.blank? && town.blank? && county.blank? && state.blank? && country.blank?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActiveModel::SecurePassword

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  field :email, type: String
  field :name, type: String
  field :password_digest, type: String
  field :api_token, type: String
  field :token_expires_at, type: String
  field :categories, type: Hash, default: {}

  index({ email: 1 }, { unique: true, name: 'email_index' })

  has_secure_password

  # associations
  has_and_belongs_to_many :locations, index: true

  # validations
  validates :email, :name, presence: true
  validates :email, format: EMAIL_REGEX, uniqueness: true
  validates :password, presence: true, length: { minimum: 4, maximum: 15 }, if: :validate_password?
  validates :api_token, uniqueness: true, allow_nil: true

  # callbacks
  before_create :generate_api_token

  # scopes

  def generate_new_token
    generate_api_token
  end

  private

  def generate_api_token
    self.token_expires_at = 1.hour.from_now

    self.api_token = loop do
      token = "#{SecureRandom.urlsafe_base64}#{Digest::SHA1.hexdigest([Time.now, rand].join)}"
      break token unless User.where(api_token: token).exists?
    end
  end

  def validate_password?
    new_record? || password.present?
  end
end

app/controllers/api/v1/locations_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class LocationsController < ApplicationController
      def create
        @data = LocationsService.new(user: @current_user, params: location_params).call

        respond_to do |format|
          format.js { head :ok }
          format.json { render json: @data, status: :ok }
        end
      end

      private

      def location_params
        params.permit(:latitude, :longitude, :formatted_address, :street_name, :town, :state, :country, :postal_code, :location_type)
      end
    end
  end
end

app/controllers/api/v1/restaurants_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class RestaurantsController < ApplicationController
      def search
        @search_results = SearchService.new(user: @current_user, params: search_params).call

        respond_to do |format|
          format.js { render 'home/search.js.erb' }
          format.json { render json: @search_results, status: :ok }
        end
      end

      def preference
        UpdatePreferenceService.new(user: @current_user, params: preference_params).call

        respond_to do |format|
          format.js { head :ok }
          format.json { head :ok }
        end
      end

      private

      def search_params
        params.permit(:term, :address, :postal_code, :radius)
      end

      def preference_params
        params.permit(:categories, :vote)
      end
    end
  end
end

app/controllers/api/v1/sessions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class SessionsController < ApplicationController
      skip_before_action :authenticate_user, only: :create

      def create
        @login_results = LoginService.new(params: login_params).call

        respond_to do |format|
          format.js { render 'sessions/create.js.erb' }
          format.json { json_response }
        end
      end

      def destroy
        User.find_by!(email: request.headers[EMAIL]).update_attributes!(token_expires_at: 1.hour.ago)
        head :ok
      end

      private

      def login_params
        params.permit(:email, :password)
      end

      def json_response
        if @login_results&.dig(:data)
          render json: @login_results.dig(:data), except: %i[password_digest location_ids created_at updated_at], status: :ok
        else
          render json: { message: 'Wrong credentials' }, status: :bad_request
        end
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  API_TOKEN = 'Api-Token'
  EMAIL = 'Email'

  rescue_from Mongoid::Errors::DocumentNotFound, with: :not_found
  rescue_from Mongoid::Errors::Validations, with: :unprocessable_entity
  rescue_from SearchService::ExternalServiceError, with: :external_service_error

  before_action :authenticate_user, :destroy_session
  helper_method :current_user, :user_logged_in? # so it can be used inside views/helpers

  def current_user
    @current_user ||= User.find_by(api_token: request.headers[API_TOKEN])
  end

  def user_logged_in?
    token_valid?(current_user)
  end

  private

  def authenticate_user
    return bad_request unless request.headers[API_TOKEN] && request.headers[EMAIL]

    user = User.find_by(email: request.headers[EMAIL].downcase)

    return unauthorized unless token_valid?(user)

    @current_user = user
  end

  def not_found
    respond_to do |format|
      format.js { render 'errors/not_found.js.erb' }
      format.json { render json: { message: 'Resource not found' }, status: :not_found }
    end
  end

  # disabling CSRF token and cookies
  def destroy_session
    request.session_options[:skip] = true
  end

  def bad_request
    head :bad_request
  end

  def token_valid?(user)
    token_match?(user) && !token_expired?(user)
  end

  def token_match?(user)
    # instead of just comparing DB token with the one from the header, let's use 'secure compare' to avoid timing attacks
    ActiveSupport::SecurityUtils.secure_compare(user.api_token, request.headers[API_TOKEN])
  end

  def token_expired?(user)
    return true unless user

    Time.current > DateTime.parse(user.token_expires_at)
  end

  def unauthorized
    respond_to do |format|
      format.js { render 'errors/unauthorized.js.erb' }
      format.json { render json: { message: 'Token expired, or wrong credentials' }, status: :unauthorized }
    end
  end

  def external_service_error
    respond_to do |format|
      format.js { render 'errors/external_service_error.js.erb' }
      format.json { render json: { message: 'External Service Error or Location unsupported' }, status: :unprocessable_entity }
    end
  end

  def unprocessable_entity(error)
    respond_to do |format|
      format.js { render 'errors/unprocessable_entity.js.erb', locals: { error: error&.problem } }
      format.json { render json: { message: error.problem }, status: :unprocessable_entity }
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  skip_before_action :authenticate_user

  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def user_logged?
    current_user.present?
  end

  def format_distance(distance)
    "#{(distance / 1600).round(2)} miles"
  end
end

app/views/home/_login.html.erb
<div id="login_section">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <h3 class="title">Log in</h3>
      <br />
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4"></div>
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
      <%= form_tag(api_sessions_path(format: :js), method: :post, remote: true) do %>
        <div class="form-group col-12">
          <%= text_field_tag(:email, '', class: 'form-control', id: :email, type: 'email', required: true, placeholder: 'email', autofocus: true) %>
        </div>
        <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <%= text_field_tag(:password, '', class: 'form-control', id: :password, type: 'password', required: true, placeholder: 'password') %>
        </div>
        <br />
        <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
          <%= submit_tag('Login', class: 'btn btn-primary', data: { disable_with: 'Logging in...' }) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_main.html.erb
<div id="main_section" style="display:none;">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <h4 class="title">Search for restaurants</h4>
      <br />
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4"></div>
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
      <%= form_tag(api_search_path(format: :js), method: :post, remote: true, id: "search_form") do %>
        <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <%= text_field_tag(:address, '', class: 'form-control', id: :address, placeholder: 'Address', autofocus: true) %>
        </div>
        <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <%= text_field_tag(:postal_code, '', class: 'form-control', id: :postal_code, placeholder: 'Zip Code') %>
        </div>
        <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <%= text_field_tag(:term, '', class: 'form-control', id: :term, placeholder: 'Search for something') %>
        </div>
        <br />
        <div class="form-group col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
          <%= submit_tag('Search', id: 'search_btn', class: 'btn btn-primary', data: { disable_with: 'Searching...' }) %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= render partial: 'search_results' %>

app/views/home/_search_results.html.erb
<div id="search_results" style="display: none;">
</div>

app/views/home/index.html.erb
<%= render partial: 'login' %>
<%= render partial: 'main' %>

<a id="go_to_top_btn" href='#top'>^</a>

<div id="loader" class="lds-dual-ring hidden overlay"></div>

app/views/home/index.js.erb
<% if user_logged_in? %>
  $("#main_section").show();
  $("#login_section").hide();
  $("#search_results").html('');
<% else %>
  $("#main_section").hide();

  // clear login form
  $("#email").val('');
  $("#password").val('');

  $("#login_section").show();
<% end %>

app/views/home/search.js.erb
$("#search_results").html("<%= escape_javascript(render partial: 'restaurants/results', locals: { data: @search_results.dig(:data), message: @search_results.dig(:message) }) %>");
$("#search_results").show();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TakkoApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= ENV.fetch('GOOGLE_API_KEY', '') %>&libraries=places"></script>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="header">
            <%= link_to('Home', root_path, id: 'home_btn') %> |
            <hr>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <div id="flash_messages">
          </div>
        </div>
      </div>
    </div>
    <div id="main" class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_results.html.erb
<div class="row">
  <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 offset-2">
    <h4>Restaurants</h4>
    <br />
  </div>
</div>

<% if data.present? %>
  <% data.each do |restaurant| %>
    <div class="row">
      <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 offset-2">
        <div class="card" style="width: 100%">
        <div class="row">
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
              <%= image_tag(restaurant.image, alt: restaurant.image, class: 'image') %>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 offset-2">
              <div class="card-body">
                <h5 class="card-title"><%= restaurant.name %></h5>
                <p class="card-text categories">Categories: <%= restaurant.categories.join(', ') %></p>
                <p class="card-text">Rating: <%= restaurant.rating %></p>
                <p class="card-text">Location: <%= restaurant.location.join(', ') %></p>
                <p class="card-text">Distance: <%= format_distance(restaurant.distance) %></p>
                <p class="card-text">Review count: <%= restaurant.review_count %></p>
                <p class="card-text">Is closed: <%= restaurant.is_closed %></p>
                <p class="card-text">Price: <%= restaurant.price %></p>

                <div class="buttons">
                  <%= link_to('Discard', '#', class: 'btn btn-danger btn-sm discard', 'data-url': api_preference_path) %>
                  <%= link_to('See more', '#', 'data-redirect-to': restaurant.url, class: 'btn btn-primary btn-sm see_more', 'data-url': api_preference_path) %>
                </div>
              </div>
            </div>
        </div>
       </div>
     </div>
    </div>
    <br />
  <% end %>
<% else %>
  <div class="row">
    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 offset-2">
      <%= message %>
    </div>
  </div>
<% end %>